### ISSUE TITLE
options.connection.close not a function

### ISSUE THREAD

**Issue by chickaletta1** [devsnek/snekfetch#31] opened 2018-02-27 01:49 UTC
## Version or commit hash:
"discord.js": "^11.3.0",
    "snekfetch": "^4.0.0-rc.0"
node version 8.9.4

## Explanation of issue:
I keep getting an error that says options.connection.close is not a function, I've reinstalled snekfetch and I'm not sure why, I've done some basic troubleshooting and tried on 2 different machines but still get that error,

## Example code to reproduce:
```js
const api = "https://jsonplaceholder.typicode.com/posts";
const snek = require("snekfetch");
const Discord = require("discord.js");

module.exports.run = async (bot, message, args) => {
    snek.get(api).then(r => {
        let body = r.body;
        let id = Number(args[0]);
        if(!id) return message.channel.send("Supply an ID");
        if(isNaN(id)) return message.channel.send("Supply a valid number");

        let entry = body.find(post => post.id === id);
        if(!entry) return message.channel.send("This entry does not exist!");

        let embed = new Discord.RichEmbed()
            .setAuthor(entry.title)
            .setDescription(entry.body)
            .addField("Author ID", entry.userId)
            .setFooter("Post ID: " + entry.id);

        message.channel.send({embed: embed});
    });

}

module.exports.help = {
    name: "json"
}

```

- [ ] Issue occurs in browser
- [ x] Issue occurs in node
![this](https://user-images.githubusercontent.com/36869950/36705957-989ee3ee-1b5f-11e8-9f1d-4f7eb00e9e78.PNG)

**Comment by devsnek** [comment] 2018-02-27 01:54
duplicate of #29

**Comment by chickaletta1** [comment] 2018-02-27 20:25
Is this something that I need to fix or?

**Comment by LetsDoughNut** [comment] 2018-03-01 02:18
Update your node version

**Closed as completed** 2018-03-01 03:08 UTC

**Comment by chickaletta1** [comment] 2018-03-01 23:46
I've updated my node version to the latest version and it's still not working

**Comment by LetsDoughNut** [comment] 2018-03-02 01:16
Please ensure your version is updated to the latest:

Node: 9.7.0

If you are running a linux system, you can follow this guide to help you upgrade to the latest version. https://bakeryhosting.us/knowledgebase.php?action=displayarticle&id=3

**Comment by chickaletta1** [comment] 2018-03-03 14:57
Any suggestions then? everything is up to date

After restarting the machine it is now working, thank you guys :+1:
