### ISSUE TITLE
Consistent crashing on v4

### ISSUE THREAD

**Issue by favna** [devsnek/snekfetch#30] opened 2018-02-25 20:54 UTC
Snekfetch version or commit hash: `v4.0.0-rc.0`

Explanation of issue:

Crashing due to incorrectly called function `options.connection.close`. This happens to all my `snekfetch` using code as of v4.0.0-rc.0.

I can see that you are telling Travis to use Node v9 and any build CI attempts before that fail - is Node v9 a requirement as of Snekfetch v4 then? Currently Node v8.9.4 is still LTS and it will be [until about december 2019!](https://github.com/nodejs/Release)

Thrown error:

```
(node:20449) ExperimentalWarning: The http2 module is an experimental API.
TypeError: options.connection.close is not a function
    at Unzip.stream.once (/home/pi/.djsbots/ribbon/node_modules/snekfetch/src/node/index.js:93:30)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Example code to reproduce:
```js
const request = require('snekfetch');

async function search() {
    try {
        const word = await request.get(`https://glosbe.com/gapi/translate?from=en&dest=en&format=json&phrase=${'soul'}`);

        if (word.ok) {
            return console.log('request passed')
        }
    } catch (e) {
        console.error(e)
    }

}

search();
```

Tried to throw reproducible code on Runkit but it appears that v4 has not yet been made available there as it uses v3.6.4.

- [ ] Issue occurs in browser
- [X] Issue occurs in node

p.s. you have a typo in your issue template. You wrote `Explaination` but it is `Explanation`

**Comment by devsnek** [comment] 2018-02-25 21:11
duplicate of #29

**Closed as completed by devsnek** 2018-02-25 21:11 UTC

**Comment by favna** [comment] 2018-02-25 21:16
My bad. I should've checked closed issues.
